### ISSUE TITLE
Resize the screenshots in read-me for better view. 

### ISSUE THREAD

**Issue by IamLizu** [sazid/aiub-app#2]
@sazid, App screenshots in the readme file needs to be resized for a better view, try to make them smaller. And it would be better if a little more about the application is told/written in the readme. Great work btw :)

**Comment by sazid** [comment]
Sure! Thanks for the heads up.

**Comment by sazid** [comment]
8467cd66283a5ac2b000001e1e640197a8b4464e
@IamLizu You can check now :)
